import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/site/PageHero";
import clientsLogos from "@/assets/clients-logos.png";
const SITE="https://www.badaie.com";
export const Route=createFileRoute("/clients")({head:()=>({meta:[{title:"Our Clients | Badaie Saudi Arabia"},{name:"description",content:"View verified Badaie clients: AL AMARA, Arabian Qudra, Plant-Tech Arabia, CRCC, Esnad International and Kamco."},{property:"og:title",content:"Our Clients | Badaie"},{property:"og:description",content:"Verified clients of Badaie Heavy Gen. Cont. Est. in Saudi Arabia."},{property:"og:url",content:`${SITE}/clients`},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}],links:[{rel:"canonical",href:`${SITE}/clients`}]}),component:Clients});

const CLIENTS=["AL AMARA","Arabian Qudra","Plant-Tech Arabia","CRCC","Esnad International","Kamco"];

function Clients(){return <><PageHero eyebrow="Our Clients" title="Relationships built on service." subtitle="The verified client organizations presented by Badaie."/><section className="section-y bg-background"><div className="container-x"><div className="mx-auto max-w-4xl text-center"><p className="eyebrow">Verified Clients</p><h2 className="mt-4 text-3xl font-semibold text-navy md:text-5xl">Our client organizations.</h2><div className="mt-10 border border-border bg-card p-5 md:p-8"><img src={clientsLogos} alt="Logos of AL AMARA, Plant-Tech Arabia, Arabian Qudra, CRCC, Esnad International and Kamco" width={1022} height={316} className="mx-auto h-auto w-full"/></div></div><ul className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{CLIENTS.map(client=><li key={client} className="flex min-h-24 items-center justify-center border border-border bg-secondary px-6 text-center font-display text-lg font-semibold text-navy">{client}</li>)}</ul></div></section></>}
